### ISSUE TITLE
Full sync issues on Ankidroid

### ISSUE THREAD

**Issue by GarrisonBaird** [adamwolf/anki-sync-server#38] opened 2019-06-20 13:37 UTC
```
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:ankisyncd.users:Authentication succeeded for user ******
INFO:werkzeug:127.0.0.1 - - [20/Jun/2019 ******] "POST /sync/hostKey HTTP/1.1" 200 -
INFO:ankisyncd.CollectionThread[******]:Starting...
INFO:ankisyncd.CollectionThread[******]:Running meta(*[], **{'v': 9, 'cv': 'ankidroid,2.9alpha71,android:8.1.0:******'})
INFO:werkzeug:127.0.0.1 - - [20/Jun/2019 ******] "POST /sync/meta HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jun/2019 ******] "POST /sync/download HTTP/1.1" 403 -
```
[AnkiDroid](https://github.com/ankidroid/Anki-Android) works fine with the [original server](https://github.com/dsnopek/anki-sync-server)
The latest desktop/iOS client doesn't have any request to `/sync/download` at all, probably some API changes in newer version?

**Comment by adamwolf** [comment] 2019-06-20 17:12
Thanks for the bug report!

That's unexpected. I've been using it with AnkiDroid, both release and Ankidroid alphas, since before I pushed this to Github!

I'll switch to 2.9alpha71 and see if I can reproduce.

**Comment by adamwolf** [comment] 2019-06-20 17:15
By the way, what attracted you to this fork over others?

**Comment by GarrisonBaird** [comment] 2019-06-21 17:40
I tried first with release and it doesn't work, so I updated to alpha, and no luck with it ether.

**Comment by GarrisonBaird** [comment] 2019-06-21 17:49
The main reason is that I heard of a sync scheme change introduced in anki 2.1, so I don't dear to touch any newer version before I can get the updated sync server, I have the iOS client and I accidentally upgraded it, so now I have to... Python 3 is important as well. Your fork is the latest, so I got yours

**Comment by GarrisonBaird** [comment] 2019-06-21 18:06
Traced the source of the `download` request, it is sent when doing a fullsync. But the desktop and iOS client don't behave like this, I don't know the problem is at which side.
[HttpSyncer.java#L111](https://github.com/ankidroid/Anki-Android/blob/972fdc8759fef1368aca06f7f70d8168946b50c5/AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java#L111)
[FullSyncer.java#L80](https://github.com/ankidroid/Anki-Android/blob/972fdc8759fef1368aca06f7f70d8168946b50c5/AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java#L80)
[Connection.java#L342](https://github.com/ankidroid/Anki-Android/blob/86f77d1dd2cd18ee312ebbe8349ef20cee2e5b96/AnkiDroid/src/main/java/com/ichi2/async/Connection.java#L342)

**Comment by adamwolf** [comment] 2019-06-21 18:40
Got it.  Interesting.  I must have broken something since doing a fullsync,
because I've been using mine with Anki 2.1 for a month or two.

I'll dig into this, but it probably won't be this weekend.

**Comment by adamwolf** [comment] 2019-06-21 19:06
Oh, I forgot--I forked from https://github.com/tsudoko/anki-sync-server, and they're pretty snappy with support.  I love that you want to use mine, but if you are in an anki emergency going to them might be faster!

**Comment by GarrisonBaird** [comment] 2019-06-22 07:44
I tried with https://github.com/tsudoko/anki-sync-server, it works
```
INFO:ankisyncd:Serving HTTP on 0.0.0.0 port 27701...
INFO:ankisyncd.CollectionThread[******]:Starting...
INFO:ankisyncd.CollectionThread[******]:Running meta(*[], **{'v': 9, 'cv': 'ankidroid,2.9alpha71,android:8.1.0:******'})
INFO:ankisyncd.http:127.0.0.1 "POST /sync/meta HTTP/1.1" 200 112
INFO:ankisyncd.CollectionThread[******]:Running operation_download(*[<ankisyncd.sync_app.SyncUserSession object at 0x769c9210>], **{})
INFO:ankisyncd.http:127.0.0.1 "POST /sync/download HTTP/1.1" 200 987136
```

**Comment by GarrisonBaird** [comment] 2019-06-22 07:46
BTW, looks like `host` and `port` in `ankisyncd.conf` don't have any effect in your fork

**Comment by adamwolf** [comment] 2019-06-22 16:51
That's true.  I thought I had those as filed issues.  (It should be easy to
fix!)

**Comment by adamwolf** [comment] 2019-07-03 15:16
I can reproduce this now, btw. Full sync on the Ankidroid side does it.

**Comment by adamwolf** [comment] 2019-07-03 20:04
The issue is not actually the download url, but rather, Werkzeug chokes parsing the form data for the download request.

Wireshark shows that the form data for the /download data is missing  the final  `--Anki-sync-boundary--`.

I can build a PR for Ankidroid, but they're pretty feature-frozen for the next release, and I'm not sure they care about this.

I may have  to fix this  using some middleware that fixes bad form data.

**Comment by adamwolf** [comment] 2019-07-04 14:08
I submitted a PR to  Ankidroid, and they accepted it! This will be fixed in the next alpha!   https://github.com/ankidroid/Anki-Android/pull/5363

**Comment by adamwolf** [comment] 2019-07-08 21:13
Ankidroid 2.9 alpha 80 fixes this issue.

**Closed as completed by adamwolf** 2019-07-08 21:13 UTC

**Comment by GarrisonBaird** [comment] 2019-07-14 18:25
Nice, thanks for your work and time.
I can't believe that they write http form data manually, it's 2019 now...
